dataset_name: 'wikitext'
dataset_config_name: 'wikitext-103-raw-v1'
output_dir: './output'
num_train_epochs: 3
batch_size: 8
learning_rate: 5e-5
weight_decay: 0.01
logging_dir: './logs'
model_save_path: './saved_model'
max_length: 128